a = input('Digite algo: ')
print('O tipo primitivo dessa valor é {}'.format(type(a)))
print('So tem espaços? {}'.format(a.isspace()))
print('É um numero? {}'.format(a.isnumeric()))
print('É alfabetico? {}'.format(a.isalpha()))
print('É alfanumerico? {}'.format(a.isalnum()))
print('Esta em maiusculas? {}'.format(a.isupper()))
print('Esta em minusculas? {}'.format(a.islower()))
print('Esta capitalizada? {}'.format(a.istitle()))
